import type { PathPhase } from "./types"

// Default Network Development Path based on the strategy
export const DEFAULT_PATH: PathPhase[] = [
  {
    id: "phase-1",
    title: "Fundament",
    order: 1,
    actions: [
      {
        id: "a1-1",
        title: "LinkedIn-Headline aktualisieren",
        description: "Aktualisiere deine LinkedIn-Headline so, dass sie deine aktuelle Rolle und Expertise widerspiegelt.",
        sphere: "A",
        effort: "15 Min",
        impact: "mittel",
        status: "open",
      },
      {
        id: "a1-2",
        title: "Core-Liste erstellen",
        description: "Erstelle eine Liste von 15–25 Schlüsselpersonen aus deinem Netzwerk, die du regelmässig pflegen willst.",
        effort: "30 Min",
        impact: "hoch",
        status: "open",
      },
      {
        id: "a1-3",
        title: "Kontakte in Tend importieren",
        description: "Exportiere deine iPhone-Kontakte als vCard und importiere sie in Tend.",
        effort: "15 Min",
        impact: "hoch",
        status: "open",
      },
      {
        id: "a1-4",
        title: "Touchpoint-Intervalle definieren",
        description: "Setze für deine Core-Kontakte individuelle Touchpoint-Intervalle (z.B. 30, 60, 90 Tage).",
        effort: "20 Min",
        impact: "hoch",
        status: "open",
      },
      {
        id: "a1-5",
        title: "3 eingeschlafene Kontakte reaktivieren",
        description: "Schreibe drei Personen, mit denen du länger nicht gesprochen hast, eine kurze Nachricht.",
        effort: "15 Min",
        impact: "hoch",
        status: "open",
      },
    ],
  },
  {
    id: "phase-2",
    title: "Sichtbarkeit",
    order: 2,
    actions: [
      {
        id: "a2-1",
        title: "Ersten LinkedIn-Post veröffentlichen",
        description: "Schreibe einen Post über ein Thema aus deiner Expertise. Kein Pitch — echtes Wissen teilen.",
        sphere: "A",
        effort: "30 Min",
        impact: "mittel",
        status: "open",
      },
      {
        id: "a2-2",
        title: "5 LinkedIn-Beiträge kommentieren",
        description: "Kommentiere substanziell bei Personen aus deinem Netzwerk — nicht nur 'Toller Post'.",
        sphere: "A",
        effort: "20 Min",
        impact: "mittel",
        status: "open",
      },
      {
        id: "a2-3",
        title: "Thinking-of-you Nachricht senden",
        description: "Sende einer Person eine Nachricht ohne Agenda — einfach weil du an sie gedacht hast.",
        sphere: "D",
        effort: "10 Min",
        impact: "hoch",
        status: "open",
      },
      {
        id: "a2-4",
        title: "Kaffee-Treffen vereinbaren",
        description: "Lade eine Person aus deinem Active-Kreis zu einem Kaffee ein. Persönlich, nicht virtuell.",
        effort: "15 Min",
        impact: "hoch",
        status: "open",
      },
      {
        id: "a2-5",
        title: "Netzwerk-Sphären zuweisen",
        description: "Kategorisiere deine Kontakte in Sphären (A–E) und Zonen (Core/Active/Radar).",
        effort: "30 Min",
        impact: "mittel",
        status: "open",
      },
    ],
  },
  {
    id: "phase-3",
    title: "Aufbau",
    order: 3,
    actions: [
      {
        id: "a3-1",
        title: "Branchenverband beitreten",
        description: "Prüfe Mitgliedschaft bei SMC, ADC oder einem relevanten Branchenverband.",
        sphere: "A",
        effort: "30 Min",
        impact: "mittel",
        status: "open",
      },
      {
        id: "a3-2",
        title: "Erstes Event besuchen",
        description: "Besuche ein Networking-Event oder eine Konferenz in deiner Branche.",
        sphere: "B",
        effort: "3 Std",
        impact: "hoch",
        status: "open",
      },
      {
        id: "a3-3",
        title: "Intro-Anfrage stellen",
        description: "Bitte einen bestehenden Kontakt, dich einer relevanten Person vorzustellen.",
        sphere: "D",
        effort: "10 Min",
        impact: "hoch",
        status: "open",
      },
      {
        id: "a3-4",
        title: "Hochschule kontaktieren",
        description: "Kontaktiere HWZ oder ZHAW für ein mögliches Gastreferat zu deinem Fachthema.",
        sphere: "C",
        effort: "20 Min",
        impact: "hoch",
        status: "open",
      },
      {
        id: "a3-5",
        title: "Wöchentlichen Posting-Rhythmus starten",
        description: "Plane feste Tage für LinkedIn-Posts ein (z.B. Montag und Donnerstag).",
        sphere: "A",
        effort: "15 Min",
        impact: "mittel",
        status: "open",
      },
    ],
  },
  {
    id: "phase-4",
    title: "Beschleunigung",
    order: 4,
    actions: [
      {
        id: "a4-1",
        title: "Mastermind-Gruppe initiieren",
        description: "Stelle eine Gruppe von 4–6 Gleichgesinnten zusammen für regelmässigen Austausch.",
        sphere: "B",
        effort: "45 Min",
        impact: "sehr hoch",
        status: "open",
      },
      {
        id: "a4-2",
        title: "Speaking-Opportunity finden",
        description: "Bewirb dich als Speaker bei einer relevanten Konferenz oder einem Meetup.",
        sphere: "C",
        effort: "30 Min",
        impact: "sehr hoch",
        status: "open",
      },
      {
        id: "a4-3",
        title: "Brand Lunch Zürich planen",
        description: "Organisiere ein informelles Mittagessen mit 5–8 Personen aus der Branche.",
        sphere: "A",
        effort: "60 Min",
        impact: "sehr hoch",
        status: "open",
      },
      {
        id: "a4-4",
        title: "Artikel oder Gastbeitrag schreiben",
        description: "Schreibe einen Fachartikel für ein relevantes Medium oder Blog.",
        sphere: "C",
        effort: "2 Std",
        impact: "hoch",
        status: "open",
      },
    ],
  },
  {
    id: "phase-5",
    title: "Etablierung",
    order: 5,
    actions: [
      {
        id: "a5-1",
        title: "Advisory-Rolle prüfen",
        description: "Prüfe ob du für ein Startup oder eine Organisation als Berater einsteigen kannst.",
        sphere: "E",
        effort: "30 Min",
        impact: "sehr hoch",
        status: "open",
      },
      {
        id: "a5-2",
        title: "Eigenes Event veranstalten",
        description: "Plane ein eigenes Networking-Event oder eine Workshop-Reihe.",
        sphere: "B",
        effort: "3 Std",
        impact: "sehr hoch",
        status: "open",
      },
      {
        id: "a5-3",
        title: "Netzwerk-Review durchführen",
        description: "Analysiere dein Netzwerk: Wer ist dazugekommen? Wen hast du vernachlässigt? Wo sind Lücken?",
        effort: "45 Min",
        impact: "hoch",
        status: "open",
      },
      {
        id: "a5-4",
        title: "Give-First Bilanz ziehen",
        description: "Reflektiere: Wo hast du anderen geholfen? Wo kannst du mehr geben?",
        sphere: "D",
        effort: "20 Min",
        impact: "hoch",
        status: "open",
      },
    ],
  },
]
